DEBUG = True
DEBUG_COLOR = (125, 125, 125)
DEBUG_WIDTH = 1
DEBUG_FONT = None
DEBUG_FONT_SIZE = 18

FPS = 60

BG_CLOUDS_IMAGE_PATH = "images/Clouds.png"
BG_GRASS_IMAGE_PATH = "images/Grass.png"
TREE_IMAGE_PATH = "images/Logs.png"
BIRD_IMAGE_PATH = "images/Bird.png"

BG_IMAGE_WIDTH = 256

BG_REPEAT = 6
BG_SPEED = 0.7

SCREEN_WIDTH = BG_IMAGE_WIDTH * (BG_REPEAT - 1)
SCREEN_HEIGHT = 800

GRAVITY = 0.2

JUMP_STRENGHT = -10

MIN_VELOCITY = -6
MAX_VELOCITY = 7

SKY_COLOR = (207, 236, 247)
SEA_COLOR = (47, 172, 194)

TREE_SPAWN_PROB = 2 * FPS  # 1/2 chance per second
TREE_VELOCITY = 2.5
TREE_SCALE = 2
TREE_COLLISION_PADDING = 7
